name: java CICD workflow
run-name: java CICD workflow
on:
 push:
  branches:
   main
jobs:
 build-and-deploy:
  runs-on: ubuntu-latest
  steps:
   - name: checkout code
     uses: actions/checkout@v4.2.2

   - name: setup maven
     uses: actions/setup-maven@v2
     with:
      maven-version: 3.8.6

   - name: build and package
     run: mvn clean package

   - name: Build docker image
     run: |
      docker build -t java-maven-image:latest .
      docker tag java-maven-image:latest agarapunaveen@gmail.com/java-maven-image
   - name: Login to DockerHub
     uses: docker/login-action@v2
     with:
        username: $DOCKER_USERNAME
        password: $DOCKER_PASSWORD

   - name: Push Docker image
     uses: docker/push-action@v2
     with:
      context: .
      push: true
      tags: agarapunaveen@gmail.com/java-maven-image:latest   
