name: java CICD workflow
run-name: java CICD workflow
on:
 push:
  branches:
   main
jobs:
 build-and-deploy:
  runs-on: ubuntu-latest
  steps:
   - name: checkout code
     uses: actions/checkout@v4.2.2

   - name: setup maven
     uses: stCarolas/setup-maven@v5
     with:
      maven-version: 3.9.0

   - name: build and package
     run: mvn clean package

   - name: Build docker image
     run: |
      docker build -t java-maven-image:latest .
      docker tag java-maven-image:latest 9666651935/java-maven-image
   - name: Login to DockerHub
     uses: docker/login-action@v2
     with:
        username: 9666651935
        password: NA0709@1995!

   - name: Push Docker image
     uses: opspresso/action-docker@v0.4.0
     with:
       context: .
       push: true
       tags: 9666651935/java-maven-image:latest   
